# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tasks.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'tasks.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0btasks.proto\x12\x05tasks\"\x89\x01\n\x04Task\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05title\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\"\n\x06status\x18\x04 \x01(\x0e\x32\x12.tasks.Task.Status\"-\n\x06Status\x12\x08\n\x04OPEN\x10\x00\x12\x0f\n\x0bIN_PROGRESS\x10\x01\x12\x08\n\x04\x44ONE\x10\x02\"\x1c\n\x0eGetTaskRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"7\n\x11\x43reateTaskRequest\x12\r\n\x05title\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\"\x12\n\x10ListTasksRequest2\xa6\x01\n\x0bTaskService\x12\x33\n\nCreateTask\x12\x18.tasks.CreateTaskRequest\x1a\x0b.tasks.Task\x12-\n\x07GetTask\x12\x15.tasks.GetTaskRequest\x1a\x0b.tasks.Task\x12\x33\n\tListTasks\x12\x17.tasks.ListTasksRequest\x1a\x0b.tasks.Task0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tasks_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TASK']._serialized_start=23
  _globals['_TASK']._serialized_end=160
  _globals['_TASK_STATUS']._serialized_start=115
  _globals['_TASK_STATUS']._serialized_end=160
  _globals['_GETTASKREQUEST']._serialized_start=162
  _globals['_GETTASKREQUEST']._serialized_end=190
  _globals['_CREATETASKREQUEST']._serialized_start=192
  _globals['_CREATETASKREQUEST']._serialized_end=247
  _globals['_LISTTASKSREQUEST']._serialized_start=249
  _globals['_LISTTASKSREQUEST']._serialized_end=267
  _globals['_TASKSERVICE']._serialized_start=270
  _globals['_TASKSERVICE']._serialized_end=436
# @@protoc_insertion_point(module_scope)
